# docker-compose.yml
version: '3.7'

services: 
  flask:
    build: .
    #command: python -u app.py
    container_name: flask-container
    depends_on:
      - mongo
    ports:
      - 5000:5000
    expose:
      - 5000
    volumes:
      - ./app:/app
    working_dir: /app
    command: gunicorn --bind 0.0.0.0:5000 app:app
    environment:
      - FLASK_ENV="production"

  mongo:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - 27017:27017
    volumes:
      - ./dump:/dump